algoritmo "soma,subtração e multiplicação com números reais"
var
 N1 , N2 , SOMA , SUBTRACAO , MULTIPLICACAO, DIVISAO: REAL

inicio
escreval("digite o primeiro número: ")
leia(N1)
escreval("digite o segundo número: ")
leia(N2)
SOMA <- N1 + N2
SUBTRACAO <- N1 - N2
MULTIPLICACAO <- N1 * N2
DIVISAO <- N1 / N2
escreval ("soma = " ,SOMA)
escreval (" subtracao = " ,SUBTRACAO)
escreval ("multiplicacao = ", MULTIPLICACAO)
escreval ("divisao = " , DIVISAO)

fimalgoritmo